<?php if (Auth::get('privilegio')== 'ADMINISTRADOR') {
    View::partial('menu-combust');
    $style = 'margin-top: 130px';
}  else {
    $style = 'margin-top: 130px';
} ?>

<div class="wrapper">
    <?php if (Auth::get('privilegio') == 'ADMINISTRADOR') { ?>
        <div class="header">
        </div>
    <?php } ?>
    <div class="main main-raised">
        <div class="container" style="<?php echo $style ?>">             
            <?php View::content() ?>
            <div class="container">
                <div class="title">
                    <h3>Tus Solicitudes de Soporte</h3>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <button type="button" rel="tooltip" title="Nueva Solicitud" class="btn btn-info btn-round btn-sm" data-toggle="modal" data-target="#myModal">
                            <i class="material-icons">comment</i>
                            Nuevo
                        </button>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="table-responsive">
                    <div class="col-md-12">
                        <?php if (count($page->items) > 0) { ?>                        
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>U. de Negocio</th>
                                        <th>T. de Problema</th>
                                        <th>Prioridad</th>
                                        <th class="text-center" style="width: 500px">Descripción</th>
                                        <th>Estado</th>                                                
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($page->items as $listado): ?> 
                                        <tr>
                                            <td><?php echo $listado->id ?></td>
                                            <td><?php echo $listado->getUnegocio()->nombre ?></td>
                                            <td><?php echo $listado->tproblema ?></td>
                                            <td><?php echo $listado->prioridad == 1 ? 'BAJA' : ($listado->prioridad == 2 ? 'MEDIA' : 'ALTA') ?></td>
                                            <td><?php echo $listado->descripcion ?></td>
                                            <td>
                                                <?php echo $listado->estado == 0 ? '<i class="material-icons">lock_open</i>' : '<i class="material-icons">lock_outline</i>' ?>
                                                <?php echo $listado->estado == 0 ? '' : '<a rel="tooltip" title="Ver Respuesta" href="#" data-id="' . $listado->respuesta . '" class="open-Modal-respuesta" data-toggle="modal" data-target="#myModal-respuesta">
                                                            <i class="material-icons" style="margin-top: -15px">visibility</i>
                                                        </a>' ?>
                                            </td>                                                   
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        <?php } else { ?>
                            <h2>No hay ningún registro</h2>
                        <?php } ?>
                        <?php View::partial('paginators/classic', false, array('page' => $page, 'url' => 'soporte/solicitudes')); ?>
                    </div>

                </div>
            </div>               
        </div>
    </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <?php echo Form::open('soporte/nuevo/') ?>
            <?php echo Form::hidden('ssoporte.estado', '', 0) ?>
            <?php echo Form::hidden('ssoporte.users_id', '', Auth::get('id')) ?>
            <?php echo Form::hidden('ssoporte.fecha', '', date('d-m-Y')) ?>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="material-icons">clear</i>
                </button>
                <h4 class="modal-title">Nueva Solicitud de Soporte</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="col-md-6">
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Unidad de Negocio</label>
                                <?php echo Form::dbSelect('ssoporte.unegocio_id', 'nombre', array('unegocio', 'relacion', Auth::get('id')), '', 'class="form-control" required'); ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Tipo de Problema</label>
                                <?php echo Form::select('ssoporte.tproblema', array('SOFTWARE' => 'SOFTWARE', 'HARDWARE' => 'HARDWARE', 'INTERNET' => 'INTERNET', 'RED' => 'RED', 'TELEFONIA' => 'TELEFONIA', 'CORREO' => 'CORREO'), 'class="form-control"') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Prioridad</label>
                                <?php echo Form::select('ssoporte.prioridad', array(1 => 'BAJA', 2 => 'MEDIA', 3 => 'ALTA'), 'class="form-control"') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Descripción</label>
                                <?php echo Form::textarea('ssoporte.descripcion', 'class="form-control" required') ?>
                            </div>
                        </div>                        
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-default btn-simple">Guardar</button>
                <button type="button" class="btn btn-danger btn-simple" data-dismiss="modal">Cerrar</button>
            </div>
            <?php echo Form::close() ?>
        </div>
    </div>
</div>
<div class="modal fade" id="myModal-respuesta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">           
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="limpiar();">
                    <i class="material-icons">clear</i>
                </button>
                <h4 class="modal-title">Respuesta</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="col-md-6">
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success" id="capa1">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">                
                <button type="button" class="btn btn-danger btn-simple" data-dismiss="modal" onclick="limpiar();">Cerrar</button>
            </div>           
        </div>
    </div>
</div>
