<?php
if (Auth::get('privilegio') == 'ADMINISTRADOR') {
    View::partial('menu-adq');
    $style = 'margin-top: 130px';
} else {
    $style = 'margin-top: 130px';
}
?>

<div class="wrapper">
    <?php if (Auth::get('privilegio') == 'ADMINISTRADOR') { ?>
        <div class="header">
        </div>
    <?php } ?>
    <div class="main main-raised">
        <div class="container-fluid" style="<?php echo $style ?>">
            <?php View::content() ?>
            
        </div>
    </div>
</div>
