<?php
View::template('');
?>

<?php echo Form::open('deptadq/editar/') ?>
<?php echo Form::hidden('adq.id') ?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        <i class="material-icons">clear</i>
    </button>
    <h4 class="modal-title">Editar Registro</h4>
</div>
<div class="modal-body">
    <div class="container">
        <div class="col-md-6">
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Fecha de Recepcion</label>
                    <?php echo Form::date('adq.frecep', 'class="form-control" required', date('Y-m-d', strtotime('-1 month', strtotime(date('Y-m-d'))))) ?> 
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Fecha de Emision</label>
                    <?php echo Form::date('adq.ffact', 'class="form-control" required', date('Y-m-d', strtotime('-1 month', strtotime(date('Y-m-d'))))) ?> 
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">T. Doc</label>
                    <?php echo Form::select('adq.tdoc', array('33' => '33', '61' => '61'), 'class="form-control"') ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Nº Doc</label>
                    <?php echo Form::text('adq.ndoc', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Proveedor</label>                                
                    <?php echo Form::text('adq.proveedor', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Observacion</label>
                    <?php echo Form::textarea('adq.observ', 'class="form-control" onblur="this.value=this.value.toUpperCase();"') ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Neto</label>
                    <?php echo Form::text('adq.neto', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">IVA</label>
                    <?php echo Form::text('adq.iva', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Adicional</label>
                    <?php echo Form::text('adq.adicional', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Total</label>
                    <?php echo Form::text('adq.total', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">F. Mercaderia</label>
                    <?php echo Form::date('adq.fmerca', 'class="form-control" required', date('Y-m-d', strtotime('-1 month', strtotime(date('Y-m-d'))))) ?> 
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Unidad de Negocio</label>
                    <?php echo Form::dbSelect('adq.unegocio_id', 'nombre', array('unegocio', 'relacion', Auth::get('id')), '', 'class="form-control" required'); ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Estado</label>
                    <?php echo Form::select('adq.estado', array('PENDIENTE' => 'PENDIENTE', 'TERMINADA' => 'TERMINADA', 'RECHAZADA' => 'RECHAZADA'), 'class="form-control"') ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Correlativo</label>
                    <?php echo Form::text('adq.correlativo', 'class="form-control" onblur="this.value=this.value.toUpperCase();"') ?>
                    <?php echo Form::hidden('adq.users_id', '', Auth::get('id')) ?>                                                
                </div>
            </div>                        
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-default btn-simple">Guardar</button>
    <button type="button" class="btn btn-danger btn-simple" data-dismiss="modal">Cerrar</button>
</div>
<?php echo Form::close() ?>