<?php
if (Auth::get('privilegio') == 'ADMINISTRADOR') {
    View::partial('menu-adq');
    $style = 'margin-top: 130px';
} else {
    $style = 'margin-top: 130px';
}
?>

<div class="wrapper">
    <?php if (Auth::get('privilegio') == 'ADMINISTRADOR') { ?>
        <div class="header">
        </div>
    <?php } ?>
    <div class="main main-raised">
        <div class="container-fluid" style="<?php echo $style ?>">
            <?php View::content() ?>
            <div class="container-fluid">                
                <div class="title">
                    <h3>Ver Facturas</h3>
                </div>
                <div class="col-sm-2">
                    <button type="button" rel="tooltip" title="Crear Nuevo Perfil" class="btn btn-danger btn-round btn-sm" data-toggle="modal" data-target="#myModal">
                        <i class="material-icons">account_circle</i>
                        Nuevo
                    </button>
                </div>                                             
            </div>                     
            <div class="table-responsive col-sm-12">                                                            
                <table id="dt_fact" class="table table-hover" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Fecha Recep.</th>                                    
                            <th>Fecha Fact.</th>
                            <th>Tipo de Doc.</th>
                            <th>Nº Doc.</th>
                            <th>Proveedor</th>
                            <th>Neto</th>
                            <th>IVA</th>
                            <th>Adic</th>                                        
                            <th>U. Negocio</th>
                            <th>F.R Mercad</th>
                            <th>User</th>                                        
                            <th>Observ</th>
                            <th>Correl</th>
                            <th>Estado</th>
                            <th>Acción</th>
                        </tr>
                    </thead>

                </table>                                       
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <?php echo Form::open('deptadq/nuevo/') ?>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="material-icons">clear</i>
                </button>
                <h4 class="modal-title">Nuevo Registro</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="col-md-6">
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Fecha de Recepcion</label>
                                <?php echo Form::date('adq.frecep', 'class="form-control" required', date('Y-m-d', strtotime('-1 month', strtotime(date('Y-m-d'))))) ?> 
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Fecha de Emision</label>
                                <?php echo Form::date('adq.ffact', 'class="form-control" required', date('Y-m-d', strtotime('-1 month', strtotime(date('Y-m-d'))))) ?> 
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">T. Doc</label>
                                <?php echo Form::select('adq.tdoc', array('33' => '33', '61' => '61'), 'class="form-control"') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Nº Doc</label>
                                <?php echo Form::text('adq.ndoc', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Proveedor</label>                                
                                <?php echo Form::text('adq.proveedor', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Observacion</label>
                                <?php echo Form::textarea('adq.observ', 'class="form-control" onblur="this.value=this.value.toUpperCase();"') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Neto</label>
                                <?php echo Form::text('adq.neto', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">IVA</label>
                                <?php echo Form::text('adq.iva', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Adicional</label>
                                <?php echo Form::text('adq.adicional', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Total</label>
                                <?php echo Form::text('adq.total', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">F. Mercaderia</label>
                                <?php echo Form::date('adq.fmerca', 'class="form-control" required', date('Y-m-d', strtotime('-1 month', strtotime(date('Y-m-d'))))) ?> 
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Unidad de Negocio</label>
                                <?php echo Form::dbSelect('adq.unegocio_id', 'nombre', array('unegocio', 'relacion', Auth::get('id')), '', 'class="form-control" required'); ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Estado</label>
                                <?php echo Form::select('adq.estado', array('PENDIENTE' => 'PENDIENTE', 'TERMINADA' => 'TERMINADA', 'RECHAZADA' => 'RECHAZADA'), 'class="form-control"') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Correlativo</label>
                                <?php echo Form::text('adq.correlativo', 'class="form-control" onblur="this.value=this.value.toUpperCase();"') ?>
                                <?php echo Form::hidden('adq.users_id', '', Auth::get('id')) ?>                                                
                            </div>
                        </div>                        
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-default btn-simple">Guardar</button>
                <button type="button" class="btn btn-danger btn-simple" data-dismiss="modal">Cerrar</button>
            </div>
            <?php echo Form::close() ?>
        </div>
    </div>
</div>
<div class="modal fade" id="myModal-editar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="editar-modal modal-content">

        </div>
    </div>
</div>
<div class="modal fade" id="myModal-eliminar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="eliminar-modal modal-content">

        </div>
    </div>
</div>