<div class="wrapper">
    <div class="header">

    </div>
    <div class="main main-raised">
        <div class="container" style="margin-top: 40px">
            <?php echo Form::open() ?>
            <?php echo Form::hidden('users.id') ?>
            <div class="container">
                <div class="title">
                    <h3>Editar Perfil de Usuario</h3>
                </div>                               
            </div>
            <div class="container">                
                <div class="col-md-6">
                    <div class="col-sm-5">
                        <div class="form-group label-floating has-success">
                            <label class="control-label">Nombre</label>
                            <?php echo Form::text('users.nombre', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="form-group label-floating has-success">
                            <label class="control-label">Apellido</label>
                            <?php echo Form::text('users.apellido', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="form-group label-floating has-success">
                            <label class="control-label">Fono</label>
                            <?php echo Form::text('users.fono', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="form-group label-floating has-success">
                            <label class="control-label">Email</label>
                            <?php echo Form::text('users.email', 'class="form-control" required') ?>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="form-group label-floating has-success">
                            <label class="control-label">Privilegio</label>                                
                            <?php echo Form::select('users.privilegio', array('ADMINISTRADOR' => 'ADMINISTRADOR', 'ADMIN_COMBUST' => 'ADMIN_COMBUST', 'ADMIN_ADQ' => 'ADMIN_ADQ', 'AD_TVO_COMBUST' => 'AD_TVO_COMBUST'), 'class="form-control"') ?>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="form-group label-floating has-success">
                            <label class="control-label">Password</label>
                            <?php echo Form::pass('users.pass', 'class="form-control" required') ?>
                        </div>
                    </div>
                    <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Horario</label>
                                <?php echo Form::text('users.horario', 'class="form-control" required') ?>
                            </div>
                        </div>
                </div>
            </div>
            <div class="container">
                <button type="submit" class="btn btn-success btn-round">Guardar</button>
                <?php echo '<a href="' . PUBLIC_PATH . 'users/" class="btn btn-default btn-round">Cancelar</a>'; ?>                
            </div>
            <?php echo Form::close() ?>
        </div>
    </div>

</div>   

