<div class="col-md-7">
    <div class="title">
        <h3>Menu</h3>
    </div>

    <nav class="navbar navbar-success">
        <div class="container">
            <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-index2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#">
                <div class="logo-container">
                    <div class="logo">
                        <img src="/img/material-kit/petroleo2.jpg" alt="Creative Tim Logo" rel="tooltip" title="<b>Material Kit</b> was Designed & Coded with care by the staff from <b>Creative Tim</b>" data-placement="bottom" data-html="true">
                    </div>
                    <div class="brand">
                        <h8><b>Dept. Petroleo</b></h8>                        
                    </div>
                </div>
            </a>
        </div>
            <div class="collapse navbar-collapse" id="navigation-index2">
                <ul class="nav navbar-nav">
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Solicitudes<b class="caret"></b></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li class="dropdown-header">Petroleo</li>
                            <li><a href="<?= PUBLIC_PATH ?>deptcombust/solicitud/">Ingreso</a></li>
                            <li><a href="<?= PUBLIC_PATH ?>deptcombust/versolicitud/">Ver Solicitudes</a></li>
                            <li><a href="<?= PUBLIC_PATH ?>deptcombust/listasignacion/">Asig. de Litros</a></li>
                            <li><a href="<?= PUBLIC_PATH ?>deptcombust/ingresovales/">Ingreso Vales</a></li>
                            <li><a href="<?= PUBLIC_PATH ?>deptcombust/asignaruta/">Asig. de Ruta</a></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Bencina</li>
                            <li><a href="#">En Desarrollo</a></li>                            
                        </ul>
                    </li>                    
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Vehiculos<b class="caret"></b></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li class="dropdown-header">Vehiculos</li>
                            <li><a href="<?= PUBLIC_PATH ?>vehiculos/tvehiculos/">Tipo de Vehiculos</a></li>
                            <li><a href="<?= PUBLIC_PATH ?>vehiculos/propietarios/">Propietarios</a></li>
                            <li><a href="<?= PUBLIC_PATH ?>vehiculos/">Patentes</a></li>
                            <li><a href="<?= PUBLIC_PATH ?>vehiculos/trabajos/">Trabajos</a></li>
                        </ul>
                    </li>
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">GPS<b class="caret"></b></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li class="dropdown-header">GPS</li>
                            <li><a href="<?= PUBLIC_PATH ?>gps/">Listado GPS</a></li>
                            <li><a href="<?= PUBLIC_PATH ?>gps/consulta_gps/">Consultas</a></li>                            
                        </ul>
                    </li>
                    <li><a href="<?= PUBLIC_PATH ?>deptcombust/surtidores/">Surtidores</a></li>
                    <li><a href="<?= PUBLIC_PATH ?>consultas/">Consultas</a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>
