<div class="col-md-6">
    <div class="title">
        <h3>Menu</h3>
    </div>

    <nav class="navbar navbar-danger">
        <div class="container">
            <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-index">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#">
                <div class="logo-container">
                    <div class="logo">
                        <img src="/img/material-kit/adq_1.jpg" alt="Creative Tim Logo" rel="tooltip" title="<b>Material Kit</b> was Designed & Coded with care by the staff from <b>Creative Tim</b>" data-placement="bottom" data-html="true">
                    </div>
                    <div class="brand">
                        <h8><b>Dept. Compras</b></h8>                        
                    </div>
                </div>
            </a>
        </div>

            <div class="collapse navbar-collapse" id="example-navbar">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Solicitudes
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li class="dropdown-header">Adquiciciones</li>
                            <li><a href="<?= PUBLIC_PATH ?>deptadq/solicitud">Ingreso Solicitud</a></li>
                            <li><a href="#">Ver Solicitudes</a></li>
                            <li><a href="#">Pendiente</a></li>                                                        
                        </ul>
                    </li>                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Recursos
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li class="dropdown-header">Recursos</li>
                            <li><a href="#">Articulos</a></li>
                            <li><a href="#">Parametros</a></li>                            
                        </ul>
                    </li>
                    <li><a href="<?= PUBLIC_PATH ?>deptadq/verFacturas">Facturas</a></li>
                    <li><a href="#">Consultas</a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>
