<nav class="navbar navbar-success navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-index2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="<?= PUBLIC_PATH ?>">
                <div class="logo-container">
                    <div class="logo">
                        <img src="/img/material-kit/logo_1.png" alt="Inversiones Santa Fe" rel="tooltip" title="<b>ERP Holding Santa Fe</b> facilitado por Inversiones Santa Fe S.A.</b>" data-placement="bottom" data-html="true">
                    </div>
                    <div class="brand">
                        <h8><b>Dept. Petroleo</b></h8>                        
                    </div>
                </div>
            </a>
        </div>
        <div class="collapse navbar-collapse" id="navigation-index2">
            <ul class="nav navbar-nav">
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Solicitudes<b class="caret"></b></a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <li class="dropdown-header">Petroleo</li>
                        <li><a href="<?= PUBLIC_PATH ?>deptcombust/solicitud/">Ingreso</a></li>
                        <li><a href="<?= PUBLIC_PATH ?>deptcombust/versolicitud/">Ver Solicitudes</a></li>
                        <li><a href="<?= PUBLIC_PATH ?>deptcombust/listasignacion/">Asig. de Litros</a></li>
                        <li><a href="<?= PUBLIC_PATH ?>deptcombust/ingresovales/">Ingreso Vales</a></li>
                        <li><a href="<?= PUBLIC_PATH ?>deptcombust/asignaruta/">Asig. de Ruta</a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">Bencina</li>
                        <li><a href="#">En Desarrollo</a></li>                            
                    </ul>
                </li>
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Vehiculos<b class="caret"></b></a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <li class="dropdown-header">Vehiculos</li>
                        <li><a href="<?= PUBLIC_PATH ?>vehiculos/tvehiculos/">Tipo de Vehiculos</a></li>
                        <li><a href="<?= PUBLIC_PATH ?>vehiculos/propietarios/">Propietarios</a></li>
                        <li><a href="<?= PUBLIC_PATH ?>vehiculos/">Patentes</a></li>
                        <li><a href="<?= PUBLIC_PATH ?>vehiculos/trabajos/">Trabajos</a></li>
                    </ul>
                </li>
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">GPS<b class="caret"></b></a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <li class="dropdown-header">GPS</li>
                        <li><a href="<?= PUBLIC_PATH ?>gps/">Listado GPS</a></li>
                        <li><a href="<?= PUBLIC_PATH ?>gps/consulta_gps/">Consultas</a></li>                            
                    </ul>
                </li>
                <li><a href="<?= PUBLIC_PATH ?>deptcombust/surtidores/">Surtidores</a></li>
                <li><a href="<?= PUBLIC_PATH ?>consultas/">Consultas</a></li>
                <li><a href="<?= PUBLIC_PATH ?>soporte/solicitudes">Soporte</a></li>                
            </ul>
            <ul class="nav navbar-nav navbar-right">                
                <li>
                    <a href="#pablo"><i class="material-icons">notifications_active</i></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">settings</i>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <li class="dropdown-header">Configuraciones</li>
                        <li><a href="<?= PUBLIC_PATH ?>perfil/">Perfil</a></li>                        
                        <li><a href="#">Ayuda</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Reportar un Problema</a></li>
                        <li class="divider"></li>
                        <li><a href="<?= PUBLIC_PATH ?>users/logout">Cerrar Sesión</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>