<nav class="navbar navbar-danger navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-index">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="<?= PUBLIC_PATH ?>">
                <div class="logo-container">
                    <div class="logo">
                        <img src="/img/material-kit/adq_1.jpg" alt="Inversiones Santa Fe" rel="tooltip" title="<b>ERP Holding Santa Fe</b> facilitado por Inversiones Santa Fe S.A.</b>" data-placement="bottom" data-html="true">
                    </div>
                    <div class="brand">
                        <h8><b>Dept. Compras</b></h8>                        
                    </div>
                </div>
            </a>
        </div>
        <div class="collapse navbar-collapse" id="navigation-index">
            <ul class="nav navbar-nav">
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Registros<b class="caret"></b></a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <li class="dropdown-header">Adquiciciones</li>
                        <li><a href="#">Ingreso Solicitud</a></li>
                        <li><a href="#">Ver Solicitudes</a></li>
                        <li><a href="#">Contizaciones</a></li>                        
                        <li class="divider"></li>
                        <li class="dropdown-header">Desarrollo</li>
                        <li><a href="#">En Desarrollo</a></li>                            
                    </ul>
                </li>
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Recursos<b class="caret"></b></a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <li class="dropdown-header">Seccion 1</li>
                        <li><a href="#">En desarrollo</a></li>                        
                    </ul>
                </li>   
                <li><a href="<?= PUBLIC_PATH ?>deptadq/">Facturas</a></li>
                <li><a href="#">Consultas</a></li>
                <li><a href="<?= PUBLIC_PATH ?>soporte/solicitudes">Soporte</a></li>                
            </ul>
            <ul class="nav navbar-nav navbar-right">                
                <li>
                    <a href="#pablo"><i class="material-icons">notifications_active</i></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">settings</i>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <li class="dropdown-header">Configuraciones</li>
                        <li><a href="<?= PUBLIC_PATH ?>perfil/">Perfil</a></li>                        
                        <li><a href="#">Ayuda</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Reportar un Problema</a></li>
                        <li class="divider"></li>
                        <li><a href="<?= PUBLIC_PATH ?>users/logout">Cerrar Sesión</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>