<div class="wrapper">
    <div class="header">

    </div>
    <div class="main main-raised">
        <div class="container" style="margin-top: 40px">
            <?php echo Form::open() ?>
            <?php echo Form::hidden('ccosto.id') ?>            
            <div class="container">
                <div class="title">
                    <h3>Editar Centro de Costo</h3>
                </div>                               
            </div>
            <div class="container">                
                <div class="col-md-6">
                    <div class="col-sm-5">
                        <div class="form-group label-floating has-success">
                            <label class="control-label">Nombre</label>
                            <?php echo Form::text('ccosto.nombre', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="form-group label-floating has-success">
                            <label class="control-label">Estado</label>                                
                            <?php echo Form::select('ccosto.estado', array('ACTIVO' => 'ACTIVO', 'DESACTIVADA' => 'DESACTIVADA'), 'class="form-control"') ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <button type="submit" class="btn btn-success btn-round">Guardar</button>
                <?php echo '<a href="' . PUBLIC_PATH . 'ccosto/" class="btn btn-default btn-round">Cancelar</a>'; ?>                
            </div>
            <?php echo Form::close() ?>
        </div>
    </div>

</div> 