<div class="wrapper">
    <div class="header">

    </div>
    <div class="main main-raised">
        <div class="container" style="margin-top: 40px">            
            <?php View::content() ?>
            <div class="container">
                <div class="title">
                    <h3>Centros de Costo</h3>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <button type="button" rel="tooltip" title="Crear C. de Costo" class="btn btn-info btn-round btn-sm" data-toggle="modal" data-target="#myModal">
                            <i class="material-icons">place</i>
                            Nuevo
                        </button>
                    </div>                         
                </div>                        
            </div>
            <div class="container" id="listadoUsers">
                <div class="table-responsive">
                    <div class="col-md-8">                                            
                        <table id="unegocio" class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Nombre</th>
                                        <th>Estado</th>                                                
                                        <th class="text-center">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($ccosto as $listado): ?> 
                                        <tr>
                                            <td><?php echo $listado->id ?></td>
                                            <td><?php echo $listado->nombre ?></td>
                                            <td><div class="togglebutton">
                                                    <label>
                                                        <?php echo $listado->estado == 'ACTIVO' ? '<input type="checkbox" id="' . $listado->id . '" checked="" onchange="cambiaEstado2(this.checked, this.id)">' : '<input type="checkbox" id="' . $listado->id . '" onchange="cambiaEstado2(this.checked, this.id)">'; ?>                                                             
                                                    </label>
                                                </div></td>                                                   
                                            <td class="td-actions text-right">
                                                <a rel="tooltip" title="Items" href="/items/index/<?php echo $listado->id ?>" class="btn btn-success btn-simple btn-xs">
                                                    <i class="material-icons">business_center</i>
                                                </a>                                                        
                                                <a rel="tooltip" title="Editar" href="/ccosto/editarCcosto/<?php echo $listado->id ?>" class="btn btn-success btn-simple btn-xs">
                                                    <i class="fa fa-edit"></i>
                                                </a>                                                        
                                                <a rel="tooltip" title="Remover" href="/ccosto/eliminarCcosto/<?php echo $listado->id ?>" class="btn btn-danger btn-simple btn-xs">
                                                    <i class="fa fa-times"></i>
                                                </a>                                            
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>                        
                    </div>

                </div>
            </div>                
        </div>
    </div>    
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <?php echo Form::open('ccosto/nuevo/') ?>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="material-icons">clear</i>
                </button>
                <h4 class="modal-title">Nuevo Centro de Costo</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="col-md-6">
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Nombre</label>
                                <?php echo Form::text('ccosto.nombre', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Estado</label>                                
                                <?php echo Form::select('ccosto.estado', array('ACTIVO' => 'ACTIVO', 'DESACTIVADA' => 'DESACTIVADA'), 'class="form-control"') ?>
                            </div>
                        </div>                        
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-default btn-simple">Guardar</button>
                <button type="button" class="btn btn-danger btn-simple" data-dismiss="modal">Cerrar</button>
            </div>
            <?php echo Form::close() ?>
        </div>
    </div>
</div>