<?php if (Auth::get('privilegio')== 'ADMINISTRADOR') {
    View::partial('menu-combust');
    $style = 'margin-top: 130px';
}  else {
    $style = 'margin-top: 130px';
} ?>

<div class="wrapper">
    <?php if (Auth::get('privilegio') == 'ADMINISTRADOR') { ?>
        <div class="header">
        </div>
    <?php } ?>
    <div class="main main-raised">
        <div class="container" style="<?php echo $style ?>">             
            <?php View::content() ?>
            <div class="container">
                <div class="title">
                    <h3>Lsitado GPS</h3>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <button type="button" rel="tooltip" title="Crear Propietario" class="btn btn-info btn-round btn-sm" data-toggle="modal" data-target="#myModal">
                            <i class="material-icons">place</i>
                            Nuevo
                        </button>
                    </div>                         
                </div>                        
            </div>
            <div class="container" id="listadoUsers">
                <div class="table-responsive">                    
                        <?php if ($data != null) { ?>                        
                        <table id="propietarios" class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Rut</th>
                                        <th>Nombre</th>                                                                                        
                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($data->list as $listado): ?> 
                                        <tr>
                                            <td><?php echo $listado->id ?></td>
                                            <td><?php echo $listado->length ?></td>
                                            <td><?php echo $listado->points ?></td>                                                                                               
                                            
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        <?php } else { ?>
                            <h2>No hay ningún registro</h2>
                        <?php } ?>                    
                </div>
            </div>                
        </div>
    </div>    
</div>
