<?php
if (Auth::get('privilegio') == 'ADMINISTRADOR') {
    View::partial('menu-combust');
    $style = 'margin-top: 130px';
} else {
    $style = 'margin-top: 130px';
}
$total = 0;
$patente = '';
?>

<div class="wrapper">
    <?php if (Auth::get('privilegio') == 'ADMINISTRADOR') { ?>
        <div class="header">
        </div>
    <?php } ?>
    <div class="main main-raised">
        <div class="container" style="<?php echo $style ?>">             
            <?php View::content() ?>
            <div class="container">
                <div class="title">
                    <h3>KM recorridos desde <?php echo $desde ?> hasta <?php echo $hasta ?></h3>
                </div>                                        
            </div>
            <div class="container" id="listadoUsers">
                <div class="table-responsive">                                                                  
                    <table id="list_gps" class="table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Patente</th>
                                <th>Total KM</th>                                                                
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($patentes['data'] as $item): 
                                $total = 0; 
                                $patente = $item['patente'];  ?> 
                                <tr>
                                    <td><?php echo $item['id'] ?></td>
                                    <td><?php echo $item['patente'] ?></td>
                                    <?php foreach ($listado["$patente"] as $item1): ?>
                                        <?php if ($item1['type'] == 'regular') {
                                            $total = $total+$item1['length'];
                                        } ?>
                                    <?php endforeach; ?>
                                    <td><?php echo $total ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>                                         
                </div>
            </div>
            <div class="container">
                    <?php echo Form::open('gps/exporta_general') ?>
                    <div class="row">
                        <div class="col-md-6">                            
                            <?php echo Form::hidden('exporta.desde', '', $desde) ?>
                            <?php echo Form::hidden('exporta.hasta', '', $hasta) ?>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success btn-fab-mini btn-round btn-xs" style="margin-top: 20px">
                        Descargar
                    </button>
                    <?php echo Form::close() ?>
                </div>
        </div>
    </div>    
</div>