<?php
header('Content-type: application/vnd.ms-excel; charset=UTF-8');
header('Content-Disposition: attachment;filename=Ruta.xls');
header('Pragma: no-cache');
header('Expires: 0');
?>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">            
                <div class="box-header">
                    <h3 class="box-title">Tabla de Datos</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">                                    
                    <table id="example1" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th style="text-align: center">Nº</th>
                                <th style="text-align: center">U. de Negocio</th>
                                <th style="text-align: center">F. Entrega</th>
                                <th style="text-align: center">Patente</th> 
                                <th style="text-align: center">T.Vehiculo</th>
                                <th style="text-align: center">Ubicacion</th>
                                <th style="text-align: center">L. Solicitados</th>
                                <th style="text-align: center">l. Asignados</th>                                                  
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($busqueda as $items): ?>                
                                <tr>
                                    <td style="text-align: center"><?php echo $items->solicitud_id ?></td>
                                    <td style="text-align: center"><?php echo $items->getUnegocio()->nombre ?></td>
                                    <td style="text-align: center"><?php echo $items->fentrega ?></td>
                                    <td style="text-align: center"><?php echo $items->getVehiculos()->patente ?></td>
                                    <td style="text-align: center"><?php echo $items->getVehiculos()->getTvehiculos()->nombre ?></td>
                                    <td style="text-align: center"><?php echo utf8_decode($items->ubicacion) ?></td>
                                    <td style="text-align: center"><?php echo $items->litros ?></td>
                                    <td style="text-align: center"><?php echo $items->lasignados ?></td>
                                    
                                </tr>                
                            <?php endforeach; ?>                
                        </tbody>
                        <tfoot>
                            <tr>
                                <th style="text-align: center">Nº</th>
                                <th style="text-align: center">U. de Negocio</th>
                                <th style="text-align: center">F. Entrega</th>
                                <th style="text-align: center">Patente</th> 
                                <th style="text-align: center">Vehiculo</th>
                                <th style="text-align: center">Ubicacion</th>
                                <th style="text-align: center">L. Solicitados</th>
                                <th style="text-align: center">l. Asignados</th>  
                            </tr>
                        </tfoot>
                    </table>                   
                </div>                
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
</section>   