<?php

$tlitros = 0;
$tlasig = 0;
$tlentreg = 0;
?>

<div class="wrapper">
    
        <div class="header">
        </div>
   
    <div class="main main-raised">
        <div class="container" style="<?php echo $style ?>">            
            <?php View::content() ?>
            <div class="container">
                <div class="title">
                    <h3>Solicitud Nº: <?php echo $solicitud->id ?></h3>
                </div>                
            </div>
            <div class="row">
                <div class="col-md-10">
                    <div class="col-md-6">
                        <h5 class="small"><strong>Unidad de Negocio: </strong> <?php echo $solicitud->getUnegocio()->nombre ?></h5>
                        <h5 class="small"><strong>Fecha Solicitud: </strong> <?php echo $solicitud->fecha ?></h5>
                    </div>
                    <div class="col-md-4">
                        <h5 class="small"><strong>Solicitante: </strong> <?php echo $solicitud->getUsers()->nombre ?></h5>
                        <h5 class="small"><strong>Fecha de Entrega: </strong> <?php echo $solicitud->fentrega ?></h5>
                    </div>
                </div>                
            </div>
            <div class="row">
                <div class="col-md-10">                
                    <div class="col-md-4">
                        <h5 class="small"><strong>Estado: </strong><strong class="text-success"><?php echo $solicitud->estado ?></strong></h5>                    
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="title">
                    <h5 class="small"><strong>Detalle de Solicitud: </strong></h5>
                </div>
            </div>
            <div class="container-fluid">
                <div class="col-md-12">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Patente</th>
                                <th>T. de Vehiculo</th>
                                <th>Trabajo</th>
                                <th>L. Solic</th>
                                <th>L. Asig</th>
                                <th>L. Entreg</th>
                                <th>Nº Vale</th>
                                <th>Firma</th>                        
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($solicitud->getDetalle() as $listado): ?> 
                                <tr>
                                    <td><?php echo $listado->getVehiculos()->patente ?></td>
                                    <td><?php echo $listado->getVehiculos()->getTvehiculos()->nombre ?></td>
                                    <td><?php echo $listado->trabajo ?></td>
                                    <td><?php echo $listado->litros ?></td>
                                    <td><?php echo $listado->lasignados ?></td>
                                    <td><?php echo $listado->lcargados ?></td>                            
                                    <td><?php echo $listado->nvale ?></td>
                                    <td><?php echo $listado->qrecibe ?></td>
                                </tr>                        
                                <?php
                                $tlitros = $tlitros + $listado->litros;
                                $tlasig = $tlasig + $listado->lasignados;
                                $tlentreg = $tlentreg + $listado->lcargados;
                            endforeach;
                            ?>
                        </tbody>
                    </table>
                </div>        
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-md-10">                
                        <div class="col-md-4">                    
                            <h5 class="small"><strong>Total L. Solicitados: </strong><?php echo $tlitros ?></h5>
                            <h5 class="small"><strong>Total L. Asignado: </strong><?php echo $tlasig ?></h5>                     
                            <h5 class="small"><strong>Total L. Entregados: </strong><?php echo $tlentreg ?></h5>
                        </div>
                    </div>
                </div>            
            </div>
            <div class="content">
                <button type="button" onclick='window.print();' class="btn btn-default btn-round btn-xs"><i class="fa fa-print"></i> Imprimir</button>                        
            </div>
        </div>
    </div>    
</div>