<?php if (Auth::get('privilegio')== 'ADMINISTRADOR') {
    View::partial('menu-combust');
    $style = 'margin-top: 130px';
}  else {
    $style = 'margin-top: 130px';
} ?>

<div class="wrapper">
    <?php if (Auth::get('privilegio') == 'ADMINISTRADOR') { ?>
        <div class="header">
        </div>
    <?php } ?>
    <div class="main main-raised">
        <div class="container" style="<?php echo $style ?>">
            <?php View::content() ?>
            <div class="container">               
                <div class="title">
                    <h3>Busque la solicitud a cerrar:</h3>
                </div>
                <div class="col-md-6">
                    <div class="col-sm-3">
                        <div class="form-group label-floating has-success">
                            <label class="control-label">Nº Solicitud</label>
                            <?php echo Form::text('solicitud.id', 'class="form-control" onblur="this.value=this.value.toUpperCase();"') ?>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <button type="submit" class="btn btn-success btn-fab btn-fab-mini btn-round" id="buscar-solicitud" style="margin-top: 20px">
                            <i class="material-icons">search</i>
                        </button>
                    </div>
                </div>
            </div>            
            <div class="container" style="padding-top: 10px" id="detalle">                
                
            </div>            
        </div>
    </div>
</div>