<?php
View::template('');
?>

<?php echo Form::open('deptcombust/anular/') ?>
<?php echo Form::hidden('solicitud.id') ?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        <i class="material-icons">clear</i>
    </button>
    <h4 class="modal-title">Anular Resgistro</h4>
</div>
<div class="modal-body">
    <div class="container">
        <h4 class="modal-title">¿Desea Anular esta solicitud?</h4>
    </div>
</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-default btn-simple">Aceptar</button>
    <button type="button" class="btn btn-danger btn-simple" data-dismiss="modal">Cerrar</button>
</div>
<?php echo Form::close() ?>