<?php
if (Auth::get('privilegio') == 'ADMINISTRADOR') {
    View::partial('menu-combust');
    $style = 'margin-top: 130px';
} else {
    $style = 'margin-top: 130px';
}
?>

<div class="wrapper">
    <?php if (Auth::get('privilegio') == 'ADMINISTRADOR') { ?>
        <div class="header">
        </div>
    <?php } ?>
    <div class="main main-raised">
        <div class="container" style="<?php echo $style ?>"> 
            <?php View::content() ?>
            <div class="container">           
                <div class="title">
                    <h3>Ver Solicitudes</h3>
                </div>                               
            </div>           
            <div class="table-responsive col-sm-12">                                                                 
                <table id="dt_datos2" class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>U. de Negocio</th>
                            <th>F. Solicitud</th>
                            <th>F. Entrega</th>   
                            <th>Solicitante</th>
                            <th>Estado</th>
                            <th class="text-center">Detalle</th>
                        </tr>
                    </thead>

                </table>                        
            </div>
            <?php if (Auth::get('privilegio') == 'ADMINISTRADOR' or Auth::get('privilegio') == 'ADMIN_COMBUST') { ?>
                <div class="container">
                    <?php echo Form::open('exporta/xfechatodo') ?>
                    <div class="row">
                        <div class="col-md-6">
                            <h5 class=""><strong>Exportar Registros</strong></h5>
                            <div class="col-sm-4">
                                <div class="form-group label-floating has-success">
                                    <label class="control-label">Fecha Inicial</label>
                                    <?php echo Form::date('consulta.desde', 'class="form-control" required', date('Y-m-d', strtotime('-1 month', strtotime(date('Y-m-d'))))) ?> 
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group label-floating has-success">
                                    <label class="control-label">Fecha Final</label>
                                    <?php echo Form::date('consulta.hasta', 'class="form-control" required', date('Y-m-d')) ?> 
                                </div>
                            </div>                        
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success btn-fab-mini btn-round btn-xs" style="margin-top: 20px">
                        <i class="material-icons">search</i>Descargar
                    </button>
                    <?php echo Form::close() ?>
                </div>
            <?php } else { ?>
                <div class="container">
                    <?php echo Form::open('exporta/xfechatodo') ?>
                    <div class="row">
                        <div class="col-md-6">
                            <h5 class=""><strong>Exportar Registros</strong></h5>
                            <div class="col-sm-4">
                                <div class="form-group label-floating has-success">
                                    <label class="control-label">Unidad de Negocio</label>
                                    <?php echo Form::dbSelect('consultaxune.id', 'nombre', array('unegocio', 'relacion', Auth::get('id')), '', 'class="form-control" required'); ?>                            
                                </div>
                            </div>                            
                            <div class="col-sm-4">
                                <div class="form-group label-floating has-success">
                                    <label class="control-label">Fecha Inicial</label>
                                    <?php echo Form::date('consultaxune.desde', 'class="form-control" required', date('Y-m-d', strtotime('-1 month', strtotime(date('Y-m-d'))))) ?> 
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group label-floating has-success">
                                    <label class="control-label">Fecha Final</label>
                                    <?php echo Form::date('consultaxune.hasta', 'class="form-control" required', date('Y-m-d')) ?> 
                                </div>
                            </div>                        
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success btn-fab-mini btn-round btn-xs" style="margin-top: 20px">
                        <i class="material-icons">search</i>Descargar
                    </button>
                    <?php echo Form::close() ?>
                </div>
            <?php } ?>
        </div>

    </div>
</div>
<div class="modal fade" id="myModal-detalle" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content modal-lg">

        </div>
    </div>
</div>
<div class="modal fade" id="myModal-eliminar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="eliminar-modal modal-content">

        </div>
    </div>
</div>