<?php
if (Auth::get('privilegio') == 'ADMINISTRADOR') {
    $style = 'margin-top: 130px';
} else {
    $style = 'margin-top: 130px';
}
$data1[] = array("y" => $nm3, "a" => $totales1->litros);
$data1[] = array("y" => $nm2, "a" => $totales2->litros);
$data1[] = array("y" => $nm1, "a" => $totales3->litros);
if ($totales4->litros == null) {
    $data1[] = array("y" => 'hoy', "a" => 0);
} else {
    $data1[] = array("y" => 'hoy', "a" => $totales4->litros);
}

$total1 = 0;
$total2 = 0;
$total3 = 0;
$total4 = 0;
?>

<div class="wrapper">

    <div class="main main-raised">
        <div class="container" style="<?php echo $style ?>">             
            <?php View::content() ?>
            <div class="container">
                <div class="title">
                    <h3>Bienvenido al Sistema para el Control de Combustible</h3>
                </div>                                        
            </div>
            <div class="container ">
                <div class="col-md-6">
                    <div class="form-group"> 
                        <?php if (Auth::get('privilegio') == 'AD_TVO_COMBUST') { ?>
                            <?php echo Form::dbSelect('unego', 'nombre', array('unegocio', 'relacion', Auth::get('id')), '', 'class="unego form-control" required'); ?>
                        <?php } else { ?>
                            <?php echo Form::dbSelect('unego', 'nombre', array('unegocio', 'relacion', Auth::get('id')), '- Seleccione por Unidad de Negocio -', 'class="unego form-control" required'); ?>
                        <?php } ?>
                    </div>
                    <div class="table-responsive">
                        <div id="capa1">
                            <h5>Consumos por flota en los ultimos tres meses, mas el consumo a la fecha de hoy.</h5>
                            <?php if (count($page1) > 0) { ?>                        
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>T. Vehiculo</th>
                                            <th><?php echo $nm3 ?></th>
                                            <th><?php echo $nm2 ?></th>
                                            <th><?php echo $nm1 ?></th> 
                                            <th>A la Fecha</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        foreach ($page1 as $listado):
                                            $total1 = $total1 + $listado->litros;
                                            ?> 
                                            <tr>                                            
                                                <td><?php echo '<a rel="tooltip" title="Ver Detalle" href="#" data-id="' . $listado->id . '" class="text-success open-Modal-detMacro1" data-toggle="modal" data-target="#myModal-detMacro">
                                                            ' . $listado->nombre . '</a>' ?></td>
                                                <td><?php echo number_format($listado->litros) ?></td>
                                                <?php foreach ($page2 as $listado2): ?>
                                                    <?php
                                                    if ($listado->nombre == $listado2->nombre) {
                                                        $total2 = $total2 + $listado2->litros;
                                                        ?>
                                                        <td><?php echo number_format($listado2->litros) ?></td>
                                                    <?php } ?>
                                                <?php endforeach; ?>
                                                <?php foreach ($page3 as $listado3): ?>
                                                    <?php
                                                    if ($listado->nombre == $listado3->nombre) {
                                                        $data[] = (object) array("label" => $listado3->nombre, "value" => $listado3->litros);
                                                        $total3 = $total3 + $listado3->litros;
                                                        ?>
                                                        <td><?php echo number_format($listado3->litros) ?></td>
                                                    <?php } ?>
                                                <?php endforeach; ?>
                                                <?php foreach ($page4 as $listado4): ?>
                                                    <?php
                                                    if ($listado->nombre == $listado4->nombre) {
                                                        $total4 = $total4 + $listado4->litros;
                                                        ?>
                                                        <td><?php echo number_format($listado4->litros) ?></td>
                                                    <?php } ?>
                                                <?php endforeach; ?>                                                        
                                            </tr>
                                        <?php endforeach; ?>
                                        <tr>
                                            <td>Totales</td>
                                            <td><?php echo number_format($total1) ?></td>
                                            <td><?php echo number_format($total2) ?></td>
                                            <td><?php echo number_format($total3) ?></td>
                                            <td><?php echo number_format($total4) ?></td>
                                        </tr>
                                    </tbody>
                                </table>
                            <?php } else { ?>
                                <h2>No hay ningún registro</h2>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <h3 class="text-center"><strong>Total Mes en Curso</strong></h3>
                    <div class="row" id="sales-chart" style="height: 300px; position: relative;">              
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="title">
                    <h3>Detalle de Unidades de Negocio</h3>
                </div>

                <div class="col-md-6">
                    <div class="table-responsive">
                        <?php if (count($page1) > 0) { ?>                        
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>Unidad de Negocio</th>                                        
                                        <th><?php echo $nm2 ?></th>
                                        <th><?php echo $nm1 ?></th> 
                                        <th>Diferen.</th>                                        
                                        <th>#</th>
                                        <th>Actual</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($lisune1 as $item1): ?> 
                                        <tr>                                            
                                            <td><?php echo $item1->nombre ?></td>
                                            <td><?php echo number_format($item1->litros) ?></td>
                                            <?php foreach ($lisune2 as $item2): ?>
                                                <?php if ($item1->nombre == $item2->nombre) { ?>
                                                    <td><?php echo number_format($item2->litros) ?></td>
                                                    <td style="background-color: #c8c8c8"><?php echo number_format($item2->litros - $item1->litros) ?></td>
                                                    <td><?php echo $item1->litros > $item2->litros ? '<i class="material-icons" style="color: #00c853">file_download</i>' : '<i class="material-icons" style="color: #D8000C">file_upload</i>' ?></td>
                                                <?php } ?>
                                            <?php endforeach; ?>
                                            <?php foreach ($lisune3 as $item3): ?>
                                                <?php if ($item1->nombre == $item3->nombre) { ?>
                                                    <td><?php echo number_format($item3->litros) ?></td>
                                                <?php } ?>
                                            <?php endforeach; ?>                                            
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        <?php } else { ?>
                            <h2>No hay ningún registro</h2>
                        <?php } ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <h3 class="text-center"><strong>Total de Consumos</strong></h3>
                    <div class="row" id="bar-chart" style="height: 300px;"></div>
                    <h5>Totales de litros cargados los ultimos 3 meses.</h5>
                </div>
                <?php if (Auth::get('privilegio') == 'ADMINISTRADOR' or Auth::get('privilegio') == 'ADMIN_COMBUST') { ?>
                    <div class="col-md-6">
                        <?php echo Form::open('consultas/informe', 'post', 'TARGET="_blanc"') ?>                        
                        <div class="col-sm-2">
                            <button type="submit" class="btn btn-success btn-fab-mini btn-round" style="margin-top: 20px">
                                <i class="material-icons">file_download</i>Descargar Informe General
                            </button>
                        </div>
                        <?php echo Form::close() ?>
                    </div>
                <?php } ?> 
            </div>
        </div>
    </div>    
</div>
<div class="modal fade" id="myModal-detMacro" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="material-icons">clear</i>
                </button>
                <h4 class="modal-title">Detalle por tipo de Vehiculos</h4>
            </div>
            <div class="modal-body">      
                <div class="container-fluid">
                    <div class="table-responsive col-sm-12">                                                                 
                        <table id="dt_datos5" class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Patente</th>
                                    <th>T. Vehiculo</th>
                                    <th><?php echo $nm3 ?></th>
                                    <th><?php echo $nm2 ?></th>
                                    <th><?php echo $nm1 ?></th>   
                                    <th>A la Fecha</th>                        
                                </tr>
                            </thead>
                            <tbody class="macro-modal">

                            </tbody>
                        </table>                        
                    </div>        
                </div>    
            </div>
            <div class="modal-footer">
                <?php if (Auth::get('privilegio') == 'ADMINISTRADOR' or Auth::get('privilegio') == 'ADMIN_COMBUST') { ?>
                <div id="buttons">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <div class="col-sm-3"></div>
                            <div class="col-sm-3">
                                <?php echo Form::open('exporta/detmacro', 'post', 'TARGET="_blanc"') ?>
                                <?php echo Form::hidden('macrotipo.id') ?>
                                <button type="submit" class="btn btn-success btn-round btn-xs">Exportar</button> 
                                <?php echo Form::close() ?>
                            </div>
                            <div class="col-sm-3">
                                <?php echo Form::open('consultas/detmacro', 'post', 'TARGET="_blanc"') ?>
                                <?php echo Form::hidden('macrotipo.id2') ?>
                                <button type="submit" class="btn btn-info btn-round btn-xs">Imprimir</button> 
                                <?php echo Form::close() ?>
                            </div> 
                            <div class="col-sm-3">
                                <button type="button" class="btn btn-danger btn-round btn-xs" data-dismiss="modal">Cerrar</button>
                            </div>                            
                        </div>
                    </div>
                </div>
                <?php }else{ ?> 
                <button type="button" class="btn btn-danger btn-round btn-xs" data-dismiss="modal">Cerrar</button>
                <?php } ?> 
            </div>
        </div>
    </div>
</div>

