<?php if (Auth::get('privilegio')== 'ADMINISTRADOR') {
    View::partial('menu-adq');
    $style = 'margin-top: 130px';
}  else {
    $style = 'margin-top: 30px';
} ?>

<div class="wrapper">
    <div class="header">

    </div>
    <div class="main main-raised">
        <div class="container" style="<?php echo $style ?>">            
            <?php View::content() ?>
            <div class="container">
                <div class="title">
                    <h3>Adquisiciones</h3>
                </div>                                               
            </div>                    
            <div class="container">

            </div>                          
        </div>
    </div>    
</div>  
