<?php if (Auth::get('privilegio')== 'ADMINISTRADOR') {
    View::partial('menu-combust');
    $style = 'margin-top: 130px';
}  else {
    $style = 'margin-top: 130px';
} ?>

<div class="wrapper">
    <?php if (Auth::get('privilegio') == 'ADMINISTRADOR') { ?>
        <div class="header">
        </div>
    <?php } ?>
    <div class="main main-raised">
        <div class="container" style="<?php echo $style ?>">             
            <?php View::content() ?>
            <div class="container">
                <div class="title">
                    <h3>Listado de Vehiculos</h3>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <button type="button" rel="tooltip" title="Crear Vehiculo" class="btn btn-info btn-round btn-sm" data-toggle="modal" data-target="#myModal">
                            <i class="material-icons">place</i>
                            Nuevo
                        </button>
                    </div>                         
                </div>                        
            </div>            
            <div class="container">
                <div class="table-responsive">
                    <div class="col-md-12">                                               
                            <table id="dt_vehi" class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Patente</th>
                                        <th>Marca</th>
                                        <th>Modelo</th>
                                        <th>T. de Vehiculo</th>
                                        <th>Propietario</th>
                                        <th>Rinde</th>
                                        <th>% Extra</th>
                                        <th>Marcador</th>
                                        <th>Limite</th>
                                        <th>Conteo</th>
                                        <th class="text-center">Actions</th>
                                    </tr>
                                </thead>
                                
                            </table>
                        
                    </div>

                </div>
            </div>                
        </div>
    </div>    
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <?php echo Form::open('vehiculos/nuevovehi/') ?>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="material-icons">clear</i>
                </button>
                <h4 class="modal-title">Nuevo Vehiculo</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="col-md-6">
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Patente</label>
                                <?php echo Form::text('vehiculos.patente', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Marca</label>
                                <?php echo Form::text('vehiculos.marca', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Modelo</label>
                                <?php echo Form::text('vehiculos.modelo', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">T. de Vehiculo</label>
                                <?php echo Form::dbSelect('vehiculos.tvehiculos_id', 'nombre', array('tvehiculos', 'find'), '', 'class="form-control" required'); ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Rendimiento</label>
                                <?php echo Form::text('vehiculos.rinde', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Propietario</label>
                                <?php echo Form::dbSelect('vehiculos.propietario_id', 'nombre', array('propietario', 'find'), '', 'class="form-control" required'); ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">% Extra</label>
                                <?php echo Form::text('vehiculos.delta', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">T. de Marcador</label>
                                <?php echo Form::select('vehiculos.tmarcador', array('HRS' => 'HRS', 'KM' => 'KM'), 'class="form-control" required') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Limite</label>
                                <?php echo Form::text('vehiculos.limite', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                                <?php echo Form::hidden('vehiculos.conteo', '', 0) ?>
                                <?php echo Form::hidden('vehiculos.conteotemp', '', 0) ?>
                                <?php echo Form::hidden('vehiculos.mes', '', date('m')) ?>
                            </div>
                        </div>                        
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-default btn-simple">Guardar</button>
                <button type="button" class="btn btn-danger btn-simple" data-dismiss="modal">Cerrar</button>
            </div>
            <?php echo Form::close() ?>
        </div>
    </div>
</div>
<div class="modal fade" id="myModal-editarvehi" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="editarvehi-modal modal-content">

        </div>
    </div>
</div>
<div class="modal fade" id="myModal-eliminarvehi" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="eliminarvehi-modal modal-content">

        </div>
    </div>
</div>