<?php
View::template('');
?>

<?php echo Form::open('vehiculos/editarvehi/') ?>
<?php echo Form::hidden('vehiculos.id') ?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        <i class="material-icons">clear</i>
    </button>
    <h4 class="modal-title">Editar Registro</h4>
</div>
<div class="modal-body">
    <div class="container">
        <div class="col-md-6">
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Patente</label>
                    <?php echo Form::text('vehiculos.patente', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Marca</label>
                    <?php echo Form::text('vehiculos.marca', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                </div>
            </div>   
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Modelo</label>
                    <?php echo Form::text('vehiculos.modelo', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">T. de Vehiculo</label>
                    <?php echo Form::dbSelect('vehiculos.tvehiculos_id', 'nombre', array('tvehiculos', 'find'), '', 'class="form-control" required'); ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Rendimiento</label>
                    <?php echo Form::text('vehiculos.rinde', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Propietario</label>
                    <?php echo Form::dbSelect('vehiculos.propietario_id', 'nombre', array('propietario', 'find'), '', 'class="form-control" required'); ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">% Extra</label>
                    <?php echo Form::text('vehiculos.delta', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">T. de Marcador</label>
                    <?php echo Form::select('vehiculos.tmarcador', array('HRS' => 'HRS', 'KM' => 'KM'), 'class="form-control" required') ?>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="form-group label-floating has-success">
                    <label class="control-label">Limite</label>
                    <?php echo Form::text('vehiculos.limite', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                    <?php echo Form::hidden('vehiculos.conteo', '', 0) ?>
                    <?php echo Form::hidden('vehiculos.conteotemp', '', 0) ?>
                    <?php echo Form::hidden('vehiculos.mes', '', date('m')) ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-default btn-simple">Guardar</button>
    <button type="button" class="btn btn-danger btn-simple" data-dismiss="modal">Cerrar</button>
</div>
<?php echo Form::close() ?>