<?php if (Auth::get('privilegio')== 'ADMINISTRADOR') {
    View::partial('menu-combust');
    $style = 'margin-top: 130px';
}  else {
    $style = 'margin-top: 130px';
} ?>

<div class="wrapper">
    <?php if (Auth::get('privilegio') == 'ADMINISTRADOR') { ?>
        <div class="header">
        </div>
    <?php } ?>
    <div class="main main-raised">
        <div class="container" style="<?php echo $style ?>">            
            <?php View::content() ?>
            <div class="container">
                <div class="title">
                    <h3>Tipos de Vehiculos</h3>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <button type="button" rel="tooltip" title="Crear T. Vehiculo" class="btn btn-info btn-round btn-sm" data-toggle="modal" data-target="#myModal">
                            <i class="material-icons">place</i>
                            Nuevo
                        </button>
                    </div>                         
                </div>                        
            </div>
            <div class="container" id="listadoUsers">
                <div class="table-responsive">                                                                    
                        <table id="tvehiculos" class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Nombre</th>                                                                                        
                                        <th class="text-center">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($page as $listado): ?> 
                                        <tr>
                                            <td><?php echo $listado->id ?></td>
                                            <td><?php echo $listado->nombre ?></td>                                                                                               
                                            <td class="td-actions text-center">                                                                                                       
                                                <a rel="tooltip" title="Editar" href="/vehiculos/editartipo/<?php echo $listado->id ?>" class="btn btn-success btn-simple btn-xs">
                                                    <i class="fa fa-edit"></i>
                                                </a> 
                                                <a rel="tooltip" title="Relacionar Trabajos" href="/vehiculos/relacion_tvtb/<?php echo $listado->id ?>" class="btn btn-success btn-simple btn-xs">
                                                    <i class="fa fa-handshake-o"></i>
                                                </a>
                                                <a rel="tooltip" title="Remover" href="/vehiculos/eliminartipo/<?php echo $listado->id ?>" class="btn btn-danger btn-simple btn-xs">
                                                    <i class="fa fa-times"></i>
                                                </a>                                            
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>                                          
                </div>
            </div>                
        </div>
    </div>    
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <?php echo Form::open('vehiculos/nuevotipo/') ?>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="material-icons">clear</i>
                </button>
                <h4 class="modal-title">Nuevo Tipo de Vehiculo</h4>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="col-md-6">
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">Nombre</label>
                                <?php echo Form::text('tvehiculos.nombre', 'class="form-control" onblur="this.value=this.value.toUpperCase();" required') ?>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group label-floating has-success">
                                <label class="control-label">T. de Vehiculo</label>
                                <?php echo Form::dbSelect('tvehiculos.macrotipo_id', 'nombre', array('macrotipo', 'find'), '', 'class="form-control" required'); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-default btn-simple">Guardar</button>
                <button type="button" class="btn btn-danger btn-simple" data-dismiss="modal">Cerrar</button>
            </div>
            <?php echo Form::close() ?>
        </div>
    </div>
</div>