<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
        <link rel="icon" type="image/png" href="assets/img/favicon.png">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

        <title>Holding Santa Fe</title>

        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

        <!--     Fonts and icons     -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

        <!-- CSS Files -->
        <?php Tag::css('material-kit/bootstrap.min') ?>
        <?php Tag::css('material-kit/material-kit') ?> 
        <?php Tag::css('material-kit/demo') ?>
        <?php Tag::css('chosen') ?> 
        <?php Tag::css('morris/morris') ?>  
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.16/af-2.2.2/b-1.5.1/cr-1.4.1/fc-3.2.4/fh-3.1.3/kt-2.3.2/r-2.2.1/rg-1.0.2/rr-1.2.3/sc-1.4.3/sl-1.2.4/datatables.min.css"/>
        <?php echo Html::includeCss() ?>
        <!-- CSS Just for demo purpose, don't include it in your project -->        

    </head>
    <body>
        <?php View::partial('menu-adquisiciones') ?>        
        <?php View::content() ?>
        <?php View::partial('footer-partial') ?>
    </body>    
    <?php echo Tag::js('material-kit/jquery.min') ?>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.16/af-2.2.2/b-1.5.1/cr-1.4.1/fc-3.2.4/fh-3.1.3/kt-2.3.2/r-2.2.1/rg-1.0.2/rr-1.2.3/sc-1.4.3/sl-1.2.4/datatables.min.js"></script>
    <?php echo Tag::js('material-kit/bootstrap.min') ?>
    <?php echo Tag::js('material-kit/material.min') ?>
    <?php echo Tag::js('material-kit/nouislider.min') ?>
   
    <?php echo Tag::js('material-kit/material-kit') ?>
    <?php echo Tag::js('jquery/erp-master') ?>
    <?php echo Tag::js('chosen/chosen.jquery') ?>
    <?php echo Tag::js('jquery/jquery.Rut') ?>
    <?php echo Tag::js('jquery/jquery.Rut.min') ?>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <?php echo Tag::js('morris/morris') ?>
    
    <script>
        $(document).on("ready", function () {          
            listadq();            
        });
        
    </script>
    
    <script>
        $(document).ready(function () {
            $(".chosen-select").chosen();
        });
    </script> 
    <script>
    $('#propietario_rut').Rut({
          on_error: function () {
            alert('Rut incorrecto');
        },
          format_on: 'keyup'
    });
</script>

</html>