<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />        
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

        <title>Holding Santa Fe</title>

        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
        <style type="text/css" media="print"> 
            div.page {  
                writing-mode: horizontal-tb; 
                height: 80%; 
                margin: 10% 0%; 
            } 
        </style>
        <!--     Fonts and icons     -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

        <!-- CSS Files -->
        <?php Tag::css('material-kit/bootstrap.min') ?>
        <?php Tag::css('material-kit/bootstrap.min', 'print') ?>
        <?php Tag::css('material-kit/material-kit') ?> 
        <?php Tag::css('material-kit/material-kit', 'print') ?> 
        <?php Tag::css('material-kit/demo') ?>
        <?php Tag::css('material-kit/demo', 'print') ?>
        <?php Tag::css('morris/morris') ?>
        <?php Tag::css('morris/morris', 'print') ?>
        <?php echo Html::includeCss() ?>
        <!-- CSS Just for demo purpose, don't include it in your project -->        

    </head>
    <body>                
        <?php View::content() ?>        
    </body>    
    <?php echo Tag::js('material-kit/jquery.min') ?>    
    <?php echo Tag::js('material-kit/bootstrap.min') ?>
    <?php echo Tag::js('material-kit/material.min') ?>
    <?php echo Tag::js('material-kit/nouislider.min') ?>

    <?php echo Tag::js('material-kit/material-kit') ?>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <?php echo Tag::js('morris/morris') ?>

    <script>
        $(function () {

            var bar = new Morris.Bar({
                element: 'bar-chart',
                resize: true,
                data: JSON.parse('<?php echo json_encode($data1) ?>'),
                barColors: ['#00a65a'],
                xkey: 'y',
                ykeys: ['a'],
                labels: ['Litros'],
                hideHover: 'auto'
            });
        });
    </script>
</html>