<div class="wrapper">
    <div class="header">

    </div>
    <div class="main main-raised">
        <div class="container" style="margin-top: 40px">           
            <?php View::content() ?>
            <div class="container">
                <div class="title">
                    <h3>Privilegios del Sistema</h3>
                </div>
                <div class="text-centert-">
                    <h7>Estos privilegios no se pueden modificar ya que estan configurados en el archivo privilegios.ini del sistema. Esta tabla es solo para poder ver los privilegios actuales del sistema.</h7>
                </div>

            </div>
            <div class="container">
                <div class="table-responsive">
                    <div class="col-md-3">                                                       
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Nombre</th>
                                </tr>
                            </thead>
                            <tbody>                                            
                                <tr>
                                    <td>1</td>
                                    <td>ADMINISTRADOR</td>                                                    
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td>ADMIN-COMBUSTIBLE</td>                                                    
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td>ADMIN-ADQUICISIONES</td>                                                    
                                </tr>
                                <tr>
                                    <td>4</td>
                                    <td>ADMIN-CGESTION</td>                                                    
                                </tr>
                                <tr>
                                    <td>5</td>
                                    <td>USUARIO-COMBUSTIBLE</td>                                                    
                                </tr>
                                <tr>
                                    <td>6</td>
                                    <td>USUARIO-ADQUISICIONES</td>                                                    
                                </tr>
                                <tr>
                                    <td>7</td>
                                    <td>USUARIO-CGESTION</td>                                                    
                                </tr>                                       
                            </tbody>
                        </table>                                                                
                    </div>
                </div>
            </div>              
        </div>
    </div>
</div>